nodename: arashdeep
port: 8000
proxies: 
 Us: 
  host: "bjsint.com"
  port: 443
  secure: true
 uk: 
  host: "pjinds.com"
  port: 443
  secure: true  
 japan: 
  host: "ads.in"
  port: 443
  secure: true  
